name: "🐛 Báo cáo lỗi (Bug Report)"
description: Báo cáo lỗi để giúp cải thiện dự án
labels: ["bug", "triage"]
body:
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Windows 11
        - Windows 10
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "v2.1.17"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "Optional"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Optional"
    validations:
      required: false
